language: node_js
node_js:
 - "0.12"

sudo: required
dist: trusty

before_script:
- npm cache clean -f
- sudo npm install -g n
- sudo n stable
- npm install -g gulp
script: bash tools/travis-deploy.sh
