language: node_js
 - "12"

sudo: required
dist: trusty

before_script:
  - npm install -g gulp-cli
  - npm install gulp@3.9.0
script:
  - npm install
  - bash tools/travis-deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: 1759e8df177c
  - COMMIT_AUTHOR_EMAIL: stefanos1316@gmail.com
