language: nodejs

sudo: required
dist: trusty
install:
- sudo apt-get install nodejs
- sudo apt-get install npm
- sudo npm install gulp-cli -g
- sudo npm install gulp -D
script: bash tools/travis-deploy.sh
after_success:
  - coveralls
env:
  global:
  - ENCRYPTION_LABEL: 1759e8df177c
  - COMMIT_AUTHOR_EMAIL: stefanos1316@gmail.com

