language: node_js
node_js:
  - "iojs"
  - "8"

sudo: required
dist: trusty

before_script:
  - supo apt-get install npm
  - sudo npm install -g gulp-cli
script: bash tools/travis-deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: 1759e8df177c
  - COMMIT_AUTHOR_EMAIL: stefanos1316@gmail.com

